apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32200
    protocol: TCP
  selector:
    app: jenkins-app
