apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql-app
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 30001
    protocol: TCP
  selector:
    app: mssql-app
